"use client"

import { Button } from "@/components/ui/button"
import { Download, Printer, Loader2 } from "lucide-react"
import { useRef, useState } from "react"
import { useToast } from "@/hooks/use-toast"

// All colors as hex — no Tailwind inside the slip (html2canvas can't parse lab() from TW v4)
const PURPLE = "#735095"
const PURPLE_LIGHT = "#f3eef8"
const PURPLE_BORDER = "#d4c5e2"
const TEXT_PRIMARY = "#1a1a1a"
const TEXT_SECONDARY = "#555555"
const TEXT_MUTED = "#888888"
const BORDER = "#d1d5db"
const WHITE = "#ffffff"
const GREEN_BG = "#f0fdf4"
const RED_BG = "#fef2f2"
const YELLOW_BG = "#fefce8"
const YELLOW_BORDER = "#facc15"
const YELLOW_TEXT = "#854d0e"

export function SalarySlipPreview({ employee }: any) {
  const slipRef = useRef<HTMLDivElement>(null)
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false)
  const { toast } = useToast()

  const employeeName = employee.employee_name || employee.employeeName || "Employee"
  const employeeId = employee.employee_id || employee.employeeId || "N/A"
  const base = Number.parseFloat(employee.basic_salary) || Number.parseFloat(employee.baseSalary) || 0

  let allowances = employee.allowances || {}
  let deductions = employee.deductions || {}

  if (Object.keys(allowances).length === 0 && employee.hra !== undefined) {
    allowances = {
      hra: employee.hra || 0, dearness_allowance: employee.dearness_allowance || 0,
      medical_allowance: employee.medical_allowance || 0, transport_allowance: employee.transport_allowance || 0,
      other_allowance: employee.other_allowance || 0,
    }
  }
  if (Object.keys(deductions).length === 0 && employee.pf_deduction !== undefined) {
    deductions = {
      pf_deduction: employee.pf_deduction || 0, esi_deduction: employee.esi_deduction || 0,
      professional_tax: employee.professional_tax || 0, loan_deduction: employee.loan_deduction || 0,
      other_deduction: employee.other_deduction || 0,
    }
  }

  const totalAllowances = Object.values(allowances).reduce((sum: number, val: any) => sum + (Number.parseFloat(val) || 0), 0)
  const totalDeductions = Object.values(deductions).reduce((sum: number, val: any) => sum + (Number.parseFloat(val) || 0), 0)

  const isAutoGenerated = !!employee.lateDays || !!employee.violationDeductions || !!employee.dailyRate
  const isProbation = employee.is_probation === true

  let leavesDeductedAmount: number
  let totalDeductionsWithLeaves: number
  let netSalary: number

  if (isAutoGenerated) {
    leavesDeductedAmount = employee.total_deductions || 0
    totalDeductionsWithLeaves = leavesDeductedAmount + totalDeductions
    netSalary = employee.net_salary || (base - leavesDeductedAmount)
  } else {
    const totalLeavesUsed = employee.total_leaves_used !== undefined
      ? employee.total_leaves_used
      : (employee.leaves_taken || 0) + (employee.leaves_deducted || 0)
    leavesDeductedAmount = base > 0 && employee.leaves_deducted > 0
      ? isProbation
        ? (base / 26) * employee.leaves_deducted
        : totalLeavesUsed >= 14 ? (base / 26) * employee.leaves_deducted : 0
      : 0
    totalDeductionsWithLeaves = totalDeductions + leavesDeductedAmount
    netSalary = base + totalAllowances - totalDeductionsWithLeaves
  }

  const currentDate = new Date()
  const monthNum = employee.month || currentDate.getMonth() + 1
  const yearNum = employee.year || currentDate.getFullYear()
  const monthNames = ['', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
  const month = monthNames[monthNum] || currentDate.toLocaleString("default", { month: "long" })
  const year = yearNum

  const fmt = (n: number) => n.toLocaleString("en-PK", { maximumFractionDigits: 0 })
  const finalTotalDeductions = totalDeductionsWithLeaves + (employee.incomeTax || 0)

  // ── PDF Download ──
  const handlePDFDownload = async () => {
    if (!slipRef.current) return
    try {
      setIsGeneratingPDF(true)
      const html2canvas = (await import('html2canvas')).default
      const jsPDF = (await import('jspdf')).jsPDF

      const el = slipRef.current
      const origMaxH = el.style.maxHeight
      const origOverflow = el.style.overflow
      el.style.maxHeight = 'none'
      el.style.overflow = 'visible'

      const canvas = await html2canvas(el, {
        scale: 2, useCORS: true, allowTaint: true, logging: false, backgroundColor: WHITE,
      })

      el.style.maxHeight = origMaxH
      el.style.overflow = origOverflow

      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF('p', 'mm', 'a4')
      const imgWidth = 190
      const pageHeight = 277
      const imgHeight = (canvas.height * imgWidth) / canvas.width
      let heightLeft = imgHeight
      let position = 10

      pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight)
      heightLeft -= pageHeight

      while (heightLeft > 0) {
        position = heightLeft - imgHeight + 10
        pdf.addPage()
        pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight)
        heightLeft -= pageHeight
      }

      pdf.save(`${employeeName.replace(/\s+/g, '_')}_SalarySlip_${month}_${year}.pdf`)
      toast({ title: "Success", description: "PDF downloaded successfully" })
    } catch (error: any) {
      console.error("PDF generation error:", error)
      toast({ title: "Error", description: `Failed to generate PDF: ${error.message || 'Unknown error'}`, variant: "destructive" })
    } finally {
      setIsGeneratingPDF(false)
    }
  }

  // ── Print ──
  const handlePrint = () => {
    if (!slipRef.current) return
    const printWindow = window.open('', '_blank', 'width=800,height=600')
    if (!printWindow) {
      toast({ title: "Error", description: "Please allow popups to print.", variant: "destructive" })
      return
    }
    printWindow.document.write(`<!DOCTYPE html><html><head><title>Salary Slip - ${employeeName} - ${month} ${year}</title>
      <style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#1a1a1a;background:#fff;padding:20px}@media print{body{padding:0}}</style>
      </head><body>${slipRef.current.innerHTML}<script>window.onload=function(){setTimeout(function(){window.print();window.close()},300)};<\/script></body></html>`)
    printWindow.document.close()
  }

  // ── Shared cell style helpers ──
  const cellL = { padding: '10px 14px', borderBottom: `1px solid ${BORDER}`, fontSize: '13px', color: TEXT_PRIMARY } as const
  const cellR = { ...cellL, textAlign: 'right' as const, fontWeight: '600' } as const

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-2">
        <Button onClick={handlePDFDownload} disabled={isGeneratingPDF} className="gap-2 w-full sm:w-auto">
          {isGeneratingPDF ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
          {isGeneratingPDF ? "Generating..." : "Download PDF"}
        </Button>
        <Button onClick={handlePrint} variant="outline" className="gap-2 bg-transparent w-full sm:w-auto">
          <Printer className="w-4 h-4" />
          Print
        </Button>
      </div>

      {/* ════════════ SALARY SLIP (all inline styles, zero Tailwind) ════════════ */}
      <div ref={slipRef} style={{ backgroundColor: WHITE, color: TEXT_PRIMARY, fontFamily: 'Arial, Helvetica, sans-serif', borderRadius: '8px', border: `1px solid ${BORDER}`, overflow: 'hidden' }}>

        {/* ── Purple Top Bar ── */}
        <div style={{ background: PURPLE, height: '6px' }} />

        <div style={{ padding: '32px 36px' }}>

          {/* ── Header ── */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingBottom: '20px', borderBottom: `2px solid ${PURPLE}`, marginBottom: '24px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
              <img src="/ovitech-logo.png" alt="OviTech Logo" style={{ height: '52px', width: 'auto' }} />
              <div>
                <div style={{ fontSize: '22px', fontWeight: '700', color: PURPLE, letterSpacing: '-0.3px' }}>OviTech Global Pvt Ltd</div>
                <div style={{ fontSize: '12px', color: TEXT_MUTED, marginTop: '2px' }}>Digital Marketing Agency</div>
              </div>
            </div>
            <div style={{ textAlign: 'right' }}>
              <div style={{ fontSize: '18px', fontWeight: '700', color: PURPLE, letterSpacing: '2px' }}>SALARY SLIP</div>
              <div style={{ fontSize: '13px', color: TEXT_SECONDARY, marginTop: '4px' }}>{month} {year}</div>
            </div>
          </div>

          {/* ── Probation Banner ── */}
          {isProbation && (
            <div style={{ background: YELLOW_BG, border: `1px solid ${YELLOW_BORDER}`, borderRadius: '6px', padding: '12px 16px', marginBottom: '20px' }}>
              <div style={{ fontWeight: '600', fontSize: '12px', color: YELLOW_TEXT }}>
                ⚠️ Probation Period — All leaves are deducted from salary.
                {employee.probation_end_date && ` (Ends: ${new Date(employee.probation_end_date).toLocaleDateString()})`}
              </div>
            </div>
          )}

          {/* ── Employee Info ── */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px', marginBottom: '28px' }}>
            <div style={{ background: '#fafafa', borderRadius: '6px', padding: '16px 18px', border: `1px solid #eee` }}>
              <div style={{ fontSize: '11px', fontWeight: '700', color: PURPLE, textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '12px' }}>Employee Information</div>
              {([
                ['Name', employeeName],
                ['Employee ID', employeeId],
                ['Email', employee.email || 'N/A'],
                ['Department', employee.department || 'N/A'],
              ] as [string, string][]).map(([label, value]) => (
                <div key={label} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', marginBottom: '6px' }}>
                  <span style={{ color: TEXT_MUTED }}>{label}</span>
                  <span style={{ fontWeight: '600', color: TEXT_PRIMARY }}>{value}</span>
                </div>
              ))}
            </div>
            <div style={{ background: '#fafafa', borderRadius: '6px', padding: '16px 18px', border: `1px solid #eee` }}>
              <div style={{ fontSize: '11px', fontWeight: '700', color: PURPLE, textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '12px' }}>Employment Details</div>
              {([
                ['Position', employee.position || 'N/A'],
                ['Joining Date', employee.joinDate || 'N/A'],
                ['Pay Period', `${month} ${year}`],
                ['Slip Date', currentDate.toLocaleDateString()],
              ] as [string, string][]).map(([label, value]) => (
                <div key={label} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', marginBottom: '6px' }}>
                  <span style={{ color: TEXT_MUTED }}>{label}</span>
                  <span style={{ fontWeight: '600', color: TEXT_PRIMARY }}>{value}</span>
                </div>
              ))}
            </div>
          </div>

          {/* ── Earnings & Deductions Tables ── */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '28px' }}>

            {/* Earnings */}
            <div style={{ border: `1px solid ${BORDER}`, borderRadius: '6px', overflow: 'hidden' }}>
              <div style={{ background: PURPLE, color: WHITE, padding: '10px 14px', display: 'flex', justifyContent: 'space-between', fontSize: '13px', fontWeight: '700' }}>
                <span>Earnings</span><span>Amount (PKR)</span>
              </div>
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', ...cellL }}>
                  <span>Basic Salary</span>
                  <span style={{ fontWeight: '600' }}>{fmt(base)}</span>
                </div>
                {Object.entries(allowances).map(([key, value]: any) => {
                  const val = Number.parseFloat(value) || 0
                  return val > 0 ? (
                    <div key={key} style={{ display: 'flex', justifyContent: 'space-between', ...cellL }}>
                      <span style={{ textTransform: 'capitalize' }}>{key.replace(/_/g, " ")}</span>
                      <span style={{ fontWeight: '600' }}>{fmt(val)}</span>
                    </div>
                  ) : null
                })}
                <div style={{ display: 'flex', justifyContent: 'space-between', padding: '12px 14px', background: GREEN_BG, fontSize: '13px', fontWeight: '700', color: TEXT_PRIMARY }}>
                  <span>Total Earnings</span>
                  <span>{fmt(base + totalAllowances)}</span>
                </div>
              </div>
            </div>

            {/* Deductions */}
            <div style={{ border: `1px solid ${BORDER}`, borderRadius: '6px', overflow: 'hidden' }}>
              <div style={{ background: '#4a4a4a', color: WHITE, padding: '10px 14px', display: 'flex', justifyContent: 'space-between', fontSize: '13px', fontWeight: '700' }}>
                <span>Deductions</span><span>Amount (PKR)</span>
              </div>
              <div>
                {deductions && typeof deductions === 'object' && Object.entries(deductions)
                  .filter(([key, value]: any) => {
                    if (!key || typeof key !== 'string' || key === '0') return false
                    return !isNaN(Number.parseFloat(String(value))) && Number.parseFloat(String(value)) > 0
                  })
                  .map(([key, value]: any) => (
                    <div key={key} style={{ display: 'flex', justifyContent: 'space-between', ...cellL }}>
                      <span style={{ textTransform: 'capitalize' }}>
                        {key === "pf_deduction" ? "Provident Fund" : key === "esi_deduction" ? "ESI" :
                          key === "professional_tax" ? "Professional Tax" : key === "loan_deduction" ? "Loan Deduction" : key.replace(/_/g, " ")}
                      </span>
                      <span style={{ fontWeight: '600' }}>{fmt(Number.parseFloat(String(value)) || 0)}</span>
                    </div>
                  ))}
                {employee.leaves_deducted > 0 && (
                  <div style={{ display: 'flex', justifyContent: 'space-between', ...cellL }}>
                    <span>Leaves Deducted ({employee.leaves_deducted} Days)</span>
                    <span style={{ fontWeight: '600' }}>{fmt(leavesDeductedAmount)}</span>
                  </div>
                )}
                {employee.incomeTax > 0 && (
                  <div style={{ display: 'flex', justifyContent: 'space-between', ...cellL }}>
                    <span>Income Tax</span>
                    <span style={{ fontWeight: '600' }}>{fmt(Number(employee.incomeTax))}</span>
                  </div>
                )}
                {/* Empty row placeholder when no deductions */}
                {finalTotalDeductions === 0 && (
                  <div style={{ display: 'flex', justifyContent: 'space-between', ...cellL }}>
                    <span style={{ color: TEXT_MUTED }}>No deductions</span>
                    <span style={{ fontWeight: '600' }}>0</span>
                  </div>
                )}
                <div style={{ display: 'flex', justifyContent: 'space-between', padding: '12px 14px', background: RED_BG, fontSize: '13px', fontWeight: '700', color: TEXT_PRIMARY }}>
                  <span>Total Deductions</span>
                  <span>{fmt(finalTotalDeductions)}</span>
                </div>
              </div>
            </div>
          </div>

          {/* ── Net Salary ── */}
          <div style={{
            background: PURPLE, borderRadius: '8px', padding: '18px 24px',
            display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '28px',
          }}>
            <span style={{ fontSize: '16px', fontWeight: '700', color: WHITE, letterSpacing: '1px' }}>NET SALARY</span>
            <span style={{ fontSize: '26px', fontWeight: '800', color: WHITE }}>
              PKR {fmt(netSalary)}
            </span>
          </div>

          {/* ── Footer ── */}
          <div style={{ borderTop: `1px solid ${BORDER}`, paddingTop: '16px', textAlign: 'center' }}>
            <div style={{ fontSize: '11px', color: TEXT_MUTED, lineHeight: '1.6' }}>
              This is a computer-generated salary slip and does not require a signature.
            </div>
            <div style={{ fontSize: '11px', color: TEXT_MUTED }}>For queries, please contact the HR Department.</div>
            <div style={{ fontSize: '12px', fontWeight: '600', color: PURPLE, marginTop: '8px' }}>
              OviTech Global Pvt Ltd &nbsp;|&nbsp; Digital Marketing Agency
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
