"use client"

import { Button } from "@/components/ui/button"
import { Download, Printer, Loader2 } from "lucide-react"
import { useRef, useState, useEffect } from "react"
import { useToast } from "@/hooks/use-toast"

export function SalarySlipPreview({ employee }: any) {
  const slipRef = useRef<HTMLDivElement>(null)
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false)
  const { toast } = useToast()

  // Support both naming conventions for compatibility
  const employeeName = employee.employee_name || employee.employeeName || "Employee"
  const employeeId = employee.employee_id || employee.employeeId || "N/A"

  const base = Number.parseFloat(employee.basic_salary) || Number.parseFloat(employee.baseSalary) || 0

  // Support both JSON object format and individual columns format
  let allowances = employee.allowances || {}
  let deductions = employee.deductions || {}

  if (Object.keys(allowances).length === 0 && employee.hra !== undefined) {
    allowances = {
      hra: employee.hra || 0,
      dearness_allowance: employee.dearness_allowance || 0,
      medical_allowance: employee.medical_allowance || 0,
      transport_allowance: employee.transport_allowance || 0,
      other_allowance: employee.other_allowance || 0,
    }
  }

  if (Object.keys(deductions).length === 0 && employee.pf_deduction !== undefined) {
    deductions = {
      pf_deduction: employee.pf_deduction || 0,
      esi_deduction: employee.esi_deduction || 0,
      professional_tax: employee.professional_tax || 0,
      loan_deduction: employee.loan_deduction || 0,
      other_deduction: employee.other_deduction || 0,
    }
  }

  const totalAllowances = Object.values(allowances).reduce(
    (sum: number, val: any) => sum + (Number.parseFloat(val) || 0),
    0,
  )
  const totalDeductions = Object.values(deductions).reduce(
    (sum: number, val: any) => sum + (Number.parseFloat(val) || 0),
    0,
  )

  // Detect auto-generated slip
  const isAutoGenerated = !!employee.lateDays || !!employee.violationDeductions || !!employee.dailyRate
  const isProbation = employee.is_probation === true

  let leavesDeductedAmount: number
  let totalDeductionsWithLeaves: number
  let netSalary: number

  if (isAutoGenerated) {
    leavesDeductedAmount = employee.total_deductions || 0
    totalDeductionsWithLeaves = leavesDeductedAmount + totalDeductions
    netSalary = employee.net_salary || (base - leavesDeductedAmount)
  } else {
    const totalLeavesUsed = employee.total_leaves_used !== undefined
      ? employee.total_leaves_used
      : (employee.leaves_taken || 0) + (employee.leaves_deducted || 0)

    leavesDeductedAmount = base > 0 && employee.leaves_deducted > 0
      ? isProbation
        ? (base / 26) * employee.leaves_deducted
        : totalLeavesUsed >= 14 ? (base / 26) * employee.leaves_deducted : 0
      : 0

    totalDeductionsWithLeaves = totalDeductions + leavesDeductedAmount
    netSalary = base + totalAllowances - totalDeductionsWithLeaves
  }

  const currentDate = new Date()
  const monthNum = employee.month || currentDate.getMonth() + 1
  const yearNum = employee.year || currentDate.getFullYear()
  const monthNames = ['', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
  const month = monthNames[monthNum] || currentDate.toLocaleString("default", { month: "long" })
  const year = yearNum

  // ── PDF Download (html2canvas + jsPDF) ──
  const handlePDFDownload = async () => {
    if (!slipRef.current) return

    try {
      setIsGeneratingPDF(true)

      const html2canvas = (await import('html2canvas')).default
      const jsPDF = (await import('jspdf')).jsPDF

      // Temporarily expand the slip for full capture
      const el = slipRef.current
      const origMaxH = el.style.maxHeight
      const origOverflow = el.style.overflow
      el.style.maxHeight = 'none'
      el.style.overflow = 'visible'

      const canvas = await html2canvas(el, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        logging: false,
        backgroundColor: '#ffffff',
      })

      // Restore
      el.style.maxHeight = origMaxH
      el.style.overflow = origOverflow

      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF('p', 'mm', 'a4')
      const imgWidth = 190 // A4 with margins
      const pageHeight = 277 // A4 with margins
      const imgHeight = (canvas.height * imgWidth) / canvas.width
      let heightLeft = imgHeight
      let position = 10 // top margin

      pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight)
      heightLeft -= pageHeight

      while (heightLeft > 0) {
        position = heightLeft - imgHeight + 10
        pdf.addPage()
        pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight)
        heightLeft -= pageHeight
      }

      const fileName = `${employeeName.replace(/\s+/g, '_')}_SalarySlip_${month}_${year}.pdf`
      pdf.save(fileName)
      toast({ title: "Success", description: "PDF downloaded successfully" })
    } catch (error: any) {
      console.error("PDF generation error:", error)
      toast({ title: "Error", description: `Failed to generate PDF: ${error.message || 'Unknown error'}`, variant: "destructive" })
    } finally {
      setIsGeneratingPDF(false)
    }
  }

  // ── Print (open slip in a new window for clean print) ──
  const handlePrint = () => {
    if (!slipRef.current) return

    const printWindow = window.open('', '_blank', 'width=800,height=600')
    if (!printWindow) {
      toast({ title: "Error", description: "Please allow popups to print.", variant: "destructive" })
      return
    }

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Salary Slip - ${employeeName} - ${month} ${year}</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Arial, Helvetica, sans-serif; color: #000; background: #fff; padding: 20px; }
          table { border-collapse: collapse; width: 100%; }
          th, td { padding: 8px 10px; text-align: left; border: 1px solid #ccc; font-size: 13px; }
          .text-right { text-align: right; }
          .font-semibold { font-weight: 600; }
          .font-bold { font-weight: 700; }
          .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #7c3aed; padding-bottom: 12px; margin-bottom: 16px; }
          .header-left { display: flex; align-items: center; gap: 12px; }
          .header-logo { height: 48px; width: auto; }
          .company-name { font-size: 20px; font-weight: bold; color: #7c3aed; }
          .company-sub { font-size: 11px; color: #666; }
          .slip-title { text-align: right; font-size: 13px; color: #666; }
          .slip-title .title { font-weight: 600; }
          .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 16px; }
          .info-section-title { font-weight: 600; font-size: 13px; color: #666; margin-bottom: 8px; }
          .info-row { font-size: 12px; margin-bottom: 4px; }
          .info-label { color: #666; font-weight: 500; }
          .tables-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px; }
          .earning-header { background: #7c3aed; color: #fff; }
          .deduction-header { background: #6b7280; color: #fff; }
          .earning-total { background: #f0fdf4; font-weight: 600; }
          .deduction-total { background: #fef2f2; font-weight: 600; }
          .net-salary { background: #f3e8ff; border: 2px solid #7c3aed; border-radius: 6px; padding: 14px 16px; display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px; }
          .net-salary .label { font-size: 16px; font-weight: 600; }
          .net-salary .amount { font-size: 22px; font-weight: 700; color: #7c3aed; }
          .footer { border-top: 2px solid #7c3aed; padding-top: 12px; text-align: center; font-size: 11px; color: #666; }
          .footer p { margin-bottom: 3px; }
          .probation-banner { background: #fefce8; border: 1px solid #facc15; border-radius: 6px; padding: 10px 14px; margin-bottom: 12px; font-size: 12px; color: #854d0e; }
          @media print { body { padding: 0; } }
        </style>
      </head>
      <body>
        ${slipRef.current.innerHTML}
        <script>
          window.onload = function() {
            setTimeout(function() { window.print(); window.close(); }, 300);
          };
        <\/script>
      </body>
      </html>
    `)
    printWindow.document.close()
  }

  return (
    <div className="space-y-4">
      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-2">
        <Button
          onClick={handlePDFDownload}
          disabled={isGeneratingPDF}
          className="gap-2 w-full sm:w-auto"
        >
          {isGeneratingPDF ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
          {isGeneratingPDF ? "Generating..." : "Download PDF"}
        </Button>
        <Button onClick={handlePrint} variant="outline" className="gap-2 bg-transparent w-full sm:w-auto">
          <Printer className="w-4 h-4" />
          Print
        </Button>
      </div>

      {/* Salary Slip Content */}
      <div ref={slipRef} className="bg-white text-black rounded-lg border border-gray-300" style={{ backgroundColor: '#ffffff', color: '#000000' }}>
        <div className="p-8 space-y-6">
          {/* Header */}
          <div className="header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2px solid #7c3aed', paddingBottom: '12px' }}>
            <div className="header-left" style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
              {/* Use regular img tag instead of Next.js Image for html2canvas compatibility */}
              <img src="/ovitech-logo.png" alt="OviTech Logo" style={{ height: '48px', width: 'auto' }} />
              <div>
                <div className="company-name" style={{ fontSize: '20px', fontWeight: 'bold', color: '#7c3aed' }}>OviTech Global Pvt Ltd</div>
                <div className="company-sub" style={{ fontSize: '11px', color: '#666' }}>Digital Marketing Agency</div>
              </div>
            </div>
            <div className="slip-title" style={{ textAlign: 'right', fontSize: '13px', color: '#666' }}>
              <div style={{ fontWeight: '600' }}>SALARY SLIP</div>
              <div style={{ fontSize: '12px' }}>{month} {year}</div>
            </div>
          </div>

          {/* Probation Banner */}
          {isProbation && (
            <div style={{ background: '#fefce8', border: '1px solid #facc15', borderRadius: '6px', padding: '10px 14px', fontSize: '12px', color: '#854d0e' }}>
              <p style={{ fontWeight: '600' }}>
                ⚠️ Probation Period: This employee is on probation. All leaves are deducted from salary.
              </p>
              {employee.probation_end_date && (
                <p style={{ fontSize: '11px', marginTop: '4px' }}>
                  Probation End Date: {new Date(employee.probation_end_date).toLocaleDateString()}
                </p>
              )}
            </div>
          )}

          {/* Employee Info */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
            <div>
              <p style={{ fontWeight: '600', fontSize: '13px', color: '#666', marginBottom: '8px' }}>Employee Information</p>
              <div style={{ fontSize: '12px' }}>
                <p style={{ marginBottom: '4px' }}><span style={{ color: '#666', fontWeight: '500' }}>Name:</span> <span style={{ fontWeight: '600' }}>{employeeName}</span></p>
                <p style={{ marginBottom: '4px' }}><span style={{ color: '#666', fontWeight: '500' }}>Employee ID:</span> <span style={{ fontWeight: '600' }}>{employeeId}</span></p>
                <p style={{ marginBottom: '4px' }}><span style={{ color: '#666', fontWeight: '500' }}>Email:</span> <span style={{ fontWeight: '600' }}>{employee.email || "N/A"}</span></p>
                <p style={{ marginBottom: '4px' }}><span style={{ color: '#666', fontWeight: '500' }}>Department:</span> <span style={{ fontWeight: '600' }}>{employee.department || "N/A"}</span></p>
              </div>
            </div>
            <div>
              <p style={{ fontWeight: '600', fontSize: '13px', color: '#666', marginBottom: '8px' }}>Employment Details</p>
              <div style={{ fontSize: '12px' }}>
                <p style={{ marginBottom: '4px' }}><span style={{ color: '#666', fontWeight: '500' }}>Position:</span> <span style={{ fontWeight: '600' }}>{employee.position || "N/A"}</span></p>
                <p style={{ marginBottom: '4px' }}><span style={{ color: '#666', fontWeight: '500' }}>Joining Date:</span> <span style={{ fontWeight: '600' }}>{employee.joinDate || "N/A"}</span></p>
                <p style={{ marginBottom: '4px' }}><span style={{ color: '#666', fontWeight: '500' }}>Slip Date:</span> <span style={{ fontWeight: '600' }}>{currentDate.toLocaleDateString()}</span></p>
              </div>
            </div>
          </div>

          {/* Earnings & Deductions Tables */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
            {/* Earnings */}
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
              <thead>
                <tr style={{ background: '#7c3aed', color: '#fff' }}>
                  <th style={{ padding: '8px 10px', textAlign: 'left', border: '1px solid #ccc' }}>Earnings</th>
                  <th style={{ padding: '8px 10px', textAlign: 'right', border: '1px solid #ccc' }}>Amount</th>
                </tr>
              </thead>
              <tbody>
                <tr style={{ borderBottom: '1px solid #ccc' }}>
                  <td style={{ padding: '8px 10px', border: '1px solid #ccc' }}>Basic Salary</td>
                  <td style={{ padding: '8px 10px', textAlign: 'right', fontWeight: '600', border: '1px solid #ccc' }}>
                    PKR {base.toLocaleString("en-PK", { maximumFractionDigits: 0 })}
                  </td>
                </tr>
                {Object.entries(allowances).map(([key, value]: any) => {
                  const val = Number.parseFloat(value) || 0
                  return val > 0 ? (
                    <tr key={key} style={{ borderBottom: '1px solid #ccc' }}>
                      <td style={{ padding: '8px 10px', border: '1px solid #ccc', textTransform: 'capitalize' }}>{key.replace(/_/g, " ")}</td>
                      <td style={{ padding: '8px 10px', textAlign: 'right', fontWeight: '600', border: '1px solid #ccc' }}>
                        PKR {val.toLocaleString("en-PK", { maximumFractionDigits: 0 })}
                      </td>
                    </tr>
                  ) : null
                })}
                <tr style={{ background: '#f0fdf4', fontWeight: '600' }}>
                  <td style={{ padding: '8px 10px', border: '1px solid #ccc' }}>Total Earnings</td>
                  <td style={{ padding: '8px 10px', textAlign: 'right', border: '1px solid #ccc' }}>
                    PKR {(base + totalAllowances).toLocaleString("en-PK", { maximumFractionDigits: 0 })}
                  </td>
                </tr>
              </tbody>
            </table>

            {/* Deductions */}
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
              <thead>
                <tr style={{ background: '#6b7280', color: '#fff' }}>
                  <th style={{ padding: '8px 10px', textAlign: 'left', border: '1px solid #ccc' }}>Deductions</th>
                  <th style={{ padding: '8px 10px', textAlign: 'right', border: '1px solid #ccc' }}>Amount</th>
                </tr>
              </thead>
              <tbody>
                {deductions && typeof deductions === 'object' && Object.entries(deductions)
                  .filter(([key, value]: any) => {
                    if (!key || typeof key !== 'string' || key === '0') return false
                    const val = Number.parseFloat(String(value))
                    return !isNaN(val) && val > 0
                  })
                  .map(([key, value]: any) => (
                    <tr key={`deduction-${key}`}>
                      <td style={{ padding: '8px 10px', border: '1px solid #ccc', textTransform: 'capitalize' }}>
                        {key === "pf_deduction" ? "PF" :
                          key === "esi_deduction" ? "ESI" :
                            key === "professional_tax" ? "Professional Tax" :
                              key === "loan_deduction" ? "Loan Deduction" :
                                key.replace(/_/g, " ")}
                      </td>
                      <td style={{ padding: '8px 10px', textAlign: 'right', fontWeight: '600', border: '1px solid #ccc' }}>
                        PKR {(Number.parseFloat(String(value)) || 0).toLocaleString("en-PK", { maximumFractionDigits: 0 })}
                      </td>
                    </tr>
                  ))}
                {employee.leaves_deducted && employee.leaves_deducted > 0 && (
                  <tr>
                    <td style={{ padding: '8px 10px', border: '1px solid #ccc' }}>Leaves Deducted ({employee.leaves_deducted} Days)</td>
                    <td style={{ padding: '8px 10px', textAlign: 'right', fontWeight: '600', border: '1px solid #ccc' }}>
                      PKR {leavesDeductedAmount.toLocaleString("en-PK", { maximumFractionDigits: 0 })}
                    </td>
                  </tr>
                )}
                {employee.incomeTax > 0 && (
                  <tr>
                    <td style={{ padding: '8px 10px', border: '1px solid #ccc' }}>Income Tax</td>
                    <td style={{ padding: '8px 10px', textAlign: 'right', fontWeight: '600', border: '1px solid #ccc' }}>
                      PKR {Number(employee.incomeTax).toLocaleString("en-PK", { maximumFractionDigits: 0 })}
                    </td>
                  </tr>
                )}
                <tr style={{ background: '#fef2f2', fontWeight: '600' }}>
                  <td style={{ padding: '8px 10px', border: '1px solid #ccc' }}>Total Deductions</td>
                  <td style={{ padding: '8px 10px', textAlign: 'right', border: '1px solid #ccc' }}>
                    PKR {(totalDeductionsWithLeaves + (employee.incomeTax || 0)).toLocaleString("en-PK", { maximumFractionDigits: 0 })}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Net Salary */}
          <div style={{ background: '#f3e8ff', border: '2px solid #7c3aed', borderRadius: '6px', padding: '14px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: '16px', fontWeight: '600' }}>NET SALARY</span>
            <span style={{ fontSize: '22px', fontWeight: '700', color: '#7c3aed' }}>
              PKR {netSalary.toLocaleString("en-PK", { maximumFractionDigits: 0 })}
            </span>
          </div>

          {/* Footer */}
          <div style={{ borderTop: '2px solid #7c3aed', paddingTop: '12px', textAlign: 'center', fontSize: '11px', color: '#666' }}>
            <p>This is a computer generated salary slip and does not require a signature.</p>
            <p>For queries, please contact HR Department</p>
            <p style={{ marginTop: '6px', fontWeight: '600' }}>OviTech Global Pvt Ltd | Digital Marketing Agency</p>
          </div>
        </div>
      </div>
    </div>
  )
}
